{% set name = "wbgapi" %}
{% set version = "1.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0d75707b9b62aaf9cadecc66d539f68277318efefcdfecf112520dcaa65b967f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.0
    - pip
    - requests
    - PyYAML
    - tabulate
  run:
    - python >=3.0
    - requests
    - PyYAML
    - tabulate

test:
  imports:
    - wbgapi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tgherzog/wbgapi
  summary: wbgapi provides a comprehensive interface to the World Banks data and metadata APIs
  description: |
    WBGAPI provides modern, pythonic access to the World Banks data API. 
    It is designed both for data novices and data scientist types.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/tgherzog/wbgapi

extra:
  recipe-maintainers:
    - NejcHirci
